spring:
  datasource:
    url: jdbc:sqlserver://nrg-server.database.windows.net:1433;database=azuredb;user=em-azure-db@nrg-server;password=Test@123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.SQLServer2012Dialect
    
server:
  port: '8083'
